services:
  - type: web
    name: pef-nfe-service
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://finance-pf.lovable.app
      - key: API_SECRET
        sync: false
